[project]
name = "backend"
version = "0.1.0"
description = ""
readme = ""
requires-python = ">=3.11"
dependencies = [
    "beanie>=1.29.0",
    "fastapi[standard]>=0.115.6",
    "pydantic>=2.10.5",
    "redis>=5.2.1",
]
